main/urls.py
# -*- coding: utf-8 -*-

from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.conf import settings
from django.views.generic.base import TemplateView

admin.autodiscover()

urlpatterns = patterns('',
    url(r'^$', TemplateView.as_view(template_name='index.html')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^profile/',include('personal.urls', namespace='personal')),
    url(r'^order/', include('order.urls',  namespace='order')),
    url(r'^dismiss_under_development_banner/$',
        'main.views.disable_under_development_banner',
        name="dismiss-under-development-banner"),
    url(r'^', include('feedback.urls')),
    url(r'^', include('announce.urls',  namespace='announce')),
    url(r'^', include('news.urls',  namespace='news')),
    url(r'^', include('services.urls',  namespace='services')),
)

if 'tinymce' in settings.INSTALLED_APPS:
    urlpatterns += patterns('',
        url(r'^tinymce/', include('tinymce.urls')),
    )

if 'filebrowser' in settings.INSTALLED_APPS:
    from filebrowser.sites import site
    urlpatterns += patterns('',
        url(r'^admin/filebrowser/', include(site.urls)),
    )

if 'grappelli' in settings.INSTALLED_APPS:
    urlpatterns += patterns('',
        url(r'^grappelli/', include('grappelli.urls')),
    )


if settings.DEBUG:
    from django.contrib.staticfiles.urls import staticfiles_urlpatterns
    urlpatterns += staticfiles_urlpatterns()
    urlpatterns += patterns('',
        url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {
            'document_root': settings.MEDIA_ROOT,
            }),
    )

urlpatterns += patterns('main.views',
    url(r'^change_theme/$', 'change_theme', name='change-theme'),
    url(r'^sitemap.xml$', 'sitemap_gen',),
)

urlpatterns += patterns('',
        url(r'^', include('catalog.urls',  namespace='catalog')),
        url(r'^', include('flatpages.urls', namespace='fpc')),
)

urlpatterns += patterns('quick_links.views',
    url(r'^(?P<slug>.*)$', 'link_detail', name='quick_link'),
)

personal/backend/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import patterns, url
from registration.views import activate
from personal.forms import RegistrationForm

urlpatterns = patterns('',
    url(r'^activate/success/$', 'personal.views.activation_complete', name='activation_complete'),
    url(r'^activate/(?P<activation_key>\w+)/$',
        activate, {'backend': 'personal.backend.RegistrationBackend', 'success_url': 'personal:activation_complete', 'template_name': 'index.html'}, name='registration_activate'),

    url(r'^register/$', 'personal.views.register', {
        'backend': 'personal.backend.RegistrationBackend',
        'form_class': RegistrationForm
    }, name='registration_register'),
)

personal/urls.py
# -*- coding: utf-8 -*-

from django.conf.urls import patterns, include, url

urlpatterns = patterns('personal.views',
    url(r'^login/$', 'login', name='auth_login'),
    url(r'^logout/$', 'logout',  name='auth_logout'),
    url(r'^changepass/$', 'edit_password', name='edit_password'),
    url(r'^password_reset/$', 'password_reset', name='password_reset'),
    url(r'^orders/$', 'list_orders', name='list_orders'),
    url(r'^$', 'edit_user_profile', name='edit_user_profile'),
    url(r'^reset/(?P<uidb36>[0-9A-Za-z]{1,13})/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        'password_reset_confirm',
        name='password_reset_confirm'),

    url(r'^', include('personal.backend.urls')),
)

personal/forms.py
# -*- coding: utf-8 -*-
import re
from django import forms
from django.contrib.auth import authenticate
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError
from django.db.models.query_utils import Q
from personal.models import UserProfile

attrs_dict = {'class': 'required'}


def validate_phone(value):
    if not re.match("^((8|\+7)[\- ]?)?(\(?\d{3}\)?[\- ]?)?[\d\- ]{6,10}", value):
        raise ValidationError(u'%s не является правильным номером' % value)


def validate_email(value):
    if not re.match("^[_a-z0-9-]+(\.[_a-z0-9-]+)*@[a-z0-9-]+(\.[a-z0-9-]+)*(\.[a-z]{2,4})$", value):
        raise ValidationError(u'%s не является корректным email' % value)


class ResetForm(forms.Form):
    email = forms.EmailField(widget=forms.TextInput(attrs=dict(attrs_dict, maxlength=75)), label="Email",
                             validators=[validate_email])


class RegistrationForm(forms.Form):
    email = forms.EmailField(widget=forms.TextInput(attrs=dict(attrs_dict, maxlength=75)), label="Email")
    first_name = forms.CharField(label=u"Имя")
    password1 = forms.CharField(widget=forms.PasswordInput(attrs=attrs_dict, render_value=False), label="Пароль")
    password2 = forms.CharField(widget=forms.PasswordInput(attrs=attrs_dict, render_value=False),
                                label="Пароль (повтор)")

    def clean_email(self):
        existing = User.objects.filter(
            Q(email__iexact=self.cleaned_data['email']) | Q(username__iexact=self.cleaned_data['email']))
        if existing.exists():
            raise forms.ValidationError(u"Этот email адрес уже используется.")
        else:
            return self.cleaned_data['email'].lower()

    def clean(self):
        if 'password1' in self.cleaned_data and 'password2' in self.cleaned_data:
            if self.cleaned_data['password1'] != self.cleaned_data['password2']:
                raise forms.ValidationError(u"Пароли не совпадают.")
        return self.cleaned_data

    def clean_password1(self):
        if 'password1' in self.cleaned_data:
            if len(self.cleaned_data['password1']) < 5:
                raise forms.ValidationError(u"Пароль слишком короткий (пароль должен быть не менее 5 символов).")
        return self.cleaned_data['password1']


class AuthenticationForm(forms.Form):
    username = forms.CharField(label=u"Email", max_length=30)
    password = forms.CharField(label=u"Пароль", widget=forms.PasswordInput)

    error_messages = {
        'invalid_login': u"Укажите корректные email и пароль. Поле пароля чувствительно к регистру символов.",
        'no_cookies': u"Ваш браузер не поддерживает cookies. Cookies необходимы для входа.",
        'inactive': u"Эта учетная запись отключена.",
    }

    def __init__(self, request=None, *args, **kwargs):
        self.request = request
        self.user_cache = None
        super(AuthenticationForm, self).__init__(*args, **kwargs)

    def clean(self):
        username = self.cleaned_data.get('username')
        password = self.cleaned_data.get('password')

        if username:
            username = username.lower()

        if username and password:
            try:
                user = User.objects.get(email = username)
                username = user.username
            except:
                pass
            self.user_cache = authenticate(username=username,
                                           password=password)
            if self.user_cache is None:
                raise forms.ValidationError(
                    self.error_messages['invalid_login'])
            elif not self.user_cache.is_active:
                raise forms.ValidationError(self.error_messages['inactive'])
        self.check_for_test_cookie()
        return self.cleaned_data

    def check_for_test_cookie(self):
        if self.request and not self.request.session.test_cookie_worked():
            raise forms.ValidationError(self.error_messages['no_cookies'])

    def get_user_id(self):
        if self.user_cache:
            return self.user_cache.id
        return None

    def get_user(self):
        return self.user_cache


class EditUserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('first_name',)


class EditUserProfileForm(forms.ModelForm):
    phone = forms.CharField(validators=[validate_phone], label=u"Телефон", required=False)

    class Meta:
        model = UserProfile
        exclude = ('user',)

personal/views.py
# -*- coding: utf-8 -*-
import base64
import pickle
from constance import config
from django.contrib import messages
from django.contrib.auth import authenticate
from django.contrib.auth import login as auth_login, logout as auth_logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.contrib.sites.models import get_current_site, Site
from django.contrib.auth.tokens import default_token_generator
from django.core.mail import EmailMessage
from django.core.urlresolvers import reverse
from django.db.models import Q
from django.http import HttpResponseRedirect, HttpResponse
from django.shortcuts import redirect, render, render_to_response
from django.template import loader, Context, Template
from django.template.loader import render_to_string
from django.views.decorators.csrf import csrf_protect
from django.utils.http import int_to_base36, base36_to_int
from registration.backends import get_backend
from registration.signals import user_registered, user_activated
from registration.models import RegistrationProfile
from main.views import simple_pagination
from order.models import Order
from personal.forms import AuthenticationForm, EditUserProfileForm, EditUserForm, ResetForm
from personal.models import UserProfile
import json
from message.models import Mail


def send_activation_email(sender, user, request, **kwargs):
    registration_profile = RegistrationProfile.objects.get(user=user)
    activation_key = registration_profile.activation_key

    context = {
        'user': user,
        'site': Site.objects.get_current(),
        'activation_key': activation_key
    }
    try:
        subject = request.activation_email.subject
        html_content = Template(request.activation_email.mail).render(Context(context))
        msg = EmailMessage(subject, html_content, config.EMAIL_FROM, [user.email])
        msg.content_subtype = "html"
        msg.send()

    except Exception, e:
        text = 'Не заполненое уведомление на почту. об отправке письма для активации %s' % e
        subject = 'Ошибка настройки сайта bshop'
        html_content = render_to_string('text.html', {'context': text})
        msg = EmailMessage(subject, html_content, config.EMAIL_FROM, [user.email])
        msg.content_subtype = "html"
        msg.send()


user_registered.connect(send_activation_email)


def send_account_activated_email(sender, user, request, **kwargs):
    context = {
        'user': user,
        'site': Site.objects.get_current()
    }

    try:
        subject = request.account_activated_email.subject
        html_content = Template(request.account_activated_email.mail).render(Context(context))

        msg = EmailMessage(subject, html_content, config.EMAIL_FROM, [user.email])
        msg.content_subtype = "html"
        msg.send()
    except Exception, e:
        text = 'Не заполненое уведомление на почту. об успешной активации. %s' % e
        subject = 'Ошибка настройки сайта bshop'
        html_content = render_to_string('text.html', {'context': text})
        msg = EmailMessage(subject, html_content, config.EMAIL_FROM, [user.email])
        msg.content_subtype = "html"
        msg.send()


user_activated.connect(send_account_activated_email)


def register(request, backend, form_class=None):
    backend = get_backend(backend)
    if form_class is None:
        form_class = backend.get_form_class(request)

    if request.method == 'POST':
        form = form_class(data=request.POST, files=request.FILES)
        if form.is_valid():
            try:
                messages.success(request, request.message_after_activation_email)
            except:
                messages.success(request,
                                 u'Вы успешно зарегистрированны, на Ваш почтовый ящик направленно письмо с информацией')

            user = backend.register(request, **form.cleaned_data)
            user_reg = User.objects.get(email=form.cleaned_data['email'])
            try:
                profile = user_reg.profile
                profile.save()
            except UserProfile.DoesNotExist:
                profile = UserProfile.objects.create(user=user_reg)
                profile.save()

        else:
            try:
                messages.success(request, request.message_after_error_reg)
            except:
                messages.success(request, u'Что то пошло не так')
            request.session['form'] = form
            return HttpResponseRedirect('/?registr=True')
    return HttpResponseRedirect('/')


def activation_complete(request):
    try:
        messages.success(request, request.message_after_successful_authentication)
    except:
        messages.success(request, u'Аккаунт успешно активированн')
    return HttpResponseRedirect('/')


@csrf_protect
def login(request, authentication_form=AuthenticationForm):
    where = "/"
    if request.META.get('HTTP_REFERER'):
        where = request.META.get('HTTP_REFERER')
    if request.method == "POST":
        form = authentication_form(data=request.POST)
        if form.is_valid():
            auth_login(request, form.get_user())
            try:
                messages.success(request, request.message_after_successful_authentication)
            except:
                messages.success(request, u'Добро пожаловать')
        else:
            try:
                messages.success(request, request.message_novalid_authentication)
            except:
                messages.success(request, u'Неверно введён логин или пароль')
            request.session['form'] = form
            return HttpResponseRedirect('/?auth=True')
    where = where.replace('/?auth=True', '')
    next_page = request.GET.get('next', where)
    if next_page:
        where = next_page
    return HttpResponseRedirect(where)


def logout(request):
    auth_logout(request)
    try:
        messages.success(request, request.message_logout)
    except:
        messages.success(request, u'Досвидания')
    try:
        return HttpResponseRedirect(request.META.get('HTTP_REFERER'))
    except:
        return HttpResponseRedirect('/')


@login_required
def edit_user_profile(request):
    user = request.user
    try:
        profile = user.profile
    except UserProfile.DoesNotExist:
        profile = UserProfile.objects.create(user=user)

    form = EditUserForm(request.POST or None, instance=user)
    profile_form = EditUserProfileForm(request.POST or None, instance=profile)
    email = user.email
    if request.method == 'POST':
        if form.is_valid() and profile_form.is_valid():
            form.save()
            profile_form.save()
            try:
                messages.success(request,request.messages_good_edit)
            except:
                messages.success(request, u'Данные успешно сохранены')
    breadcrumbs = [{'url': reverse('personal:edit_user_profile'), 'title': 'Личный кабинет'}, ]
    return render(request, 'personal/profile_edit.html',
                  {'form': form, 'profile_form': profile_form, 'email': email, 'breadcrumbs': breadcrumbs})


@login_required
def edit_password(request):
    user = request.user
    norepeat = False
    novalid = False
    if request.method == "POST":
        oldpass = request.POST.get("oldpass")
        newpass = request.POST.get("newpass")
        cnewpass = request.POST.get("cnewpass")
        user_cache = authenticate(username=user.username, password=oldpass)
        if not (user_cache is None):
            if newpass == cnewpass:
                user.set_password(newpass)
                user.save()
                try:
                    messages.success(request, request.message_after_successful_password_changing)
                except:
                    messages.success(request, u'Данные успешно сохранены')
            else:
                norepeat = True
                try:
                    messages.success(request, request.messages_pass_not_confirm)
                except:
                    messages.success(request, u'Не совпадает пароли')
        else:
            novalid = True
            try:
                messages.success(request, request.messages_not_valid_password)
            except:
                messages.success(request, u'Введён неверный пароль')

    form = EditUserForm(None, instance=user)
    profile_form = EditUserProfileForm(None, instance=user.profile)
    email = user.email
    breadcrumbs = [{'url': reverse('personal:edit_user_profile'), 'title': 'Личный кабинет'},
                   ]

    return render(request, 'personal/profile_edit.html', {'form': form, 'novalid': novalid, 'norepeat': norepeat,
                                                          'profile_form': profile_form, 'email': email,
                                                          'breadcrumbs': breadcrumbs})


@csrf_protect
def password_reset(request):
    form = ResetForm(request.POST or None)
    if request.method == "POST":

        if form.is_valid():
            email = request.POST.get("email")
            try:
                user = User.objects.filter(Q(Q(username=email) | Q(email=email)))[0]
            except:
                user = None

            if not (user is None):
                current_site = get_current_site(request)
                site_name = current_site.name
                domain = current_site.domain

                context = {
                    'domain': domain,
                    'site_name': site_name,
                    'uid': int_to_base36(user.id),
                    'token': default_token_generator.make_token(user),
                }
                try:
                    messages.success(request, request.message_after_password_reset_email)
                except:
                    messages.success(request, u'На указанную почту (%s) отправленно сообщение с инструкцией' % email)
                try:

                    subject = Mail.objects.get(type='password_reset_email').subject

templates/personal/order_list.html
{% extends 'base.html' %}

{% load flatpages_extras seo_extras services_extras order_extras catalog_extras %}
{% load thumbnail catalog_filters %}
    {% block page-seo %}
        {% load seo_extras %}
        {% get_seo item %}
    {% endblock %}

    {% block header %}
        {% include "templatetags/header.html" with url="/profile/" %}
    {% endblock %}

    {% block breadcrumbs %}
        {% include "templatetags/breadcrumbs.html" %}
    {% endblock %}

    {% block main-content %}
        <div class="main-content">
            <div class="cb" style="height: 10px;"></div>
            <div class="main-content-l lk">
                <div class="tree-menu side-menu">
                         <a class="menu-item lvl0" href="{% url 'personal:edit_user_profile' %}">
                            Личные данные
                        </a>
                        <a class="menu-item lvl0 select" href="{% url 'personal:list_orders' %}">
                            История покупок
                        </a>
                </div>
            </div>
            <div class="main-content-r tmce lk lk-top" style="border-radius:5px;">
                <h1>История покупок</h1>
                {% for item in orders %}
                    <table class="cart-items history-items">
                    <tbody>
                        <tr>
                            <th colspan="4">Заказ № {{ item.id }} от {{ item.created_at }}</th>
                        </tr>
                        {% for p in item.get_items %}
                        <tr class="cart-product{% if forloop.first %} first{% else %}{% if forloop.last %} last{% endif %}{% endif %}">
                            <td class="cart-product-image">
                                <a href="#" title="">
                                    <div class="product-image-wrapper">
                                     {% if p.product.get_primary_image %}
                                        {% with p.product.get_primary_image.file as image %}
                                        {% if image|is_portrait %}
                                            {% thumbnail image "x122" crop="center" upscale=False quality=100 as im %}
                                                <img src="{{ im.url }}" alt="{{ p.product_name }}">
                                            {% endthumbnail %}
                                        {% else %}
                                            {% thumbnail image "161" crop="center" upscale=False quality=100 as im %}
                                                <img src="{{ im.url }}" alt="{{ p.product_name }}">
                                            {% endthumbnail %}
                                        {% endif %}
                                        {% endwith %}
                                    {% else %}
                                        <img src="http://placehold.it/161x122" alt="{{ item.name }}">
                                    {% endif %}
                                    </div>
                                </a>
                            </td>
                            <td class="cart-product-details">
                                <a href="{{ p.product.get_absolute_url }}" title="{{ p.product_name }}">
                                    <div style="word-break: break-all;" class="product-title">{{ p.product_name }}</div>
                                </a>
                            </td>
                            <td class="history-product-details">
                                <div class="product-title">Количество: {{ p.p_quantity }}</div>
                            </td>
                            <td class="cart-product-total-price">
                                <div class="num">{{ p.p_sum }} руб.</div>
                            </td>
                        </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                {% endfor %}

            </div>

            <div class="cb"></div>
        <div class="list-controls history">
            {% include "templatetags/pagination.html" with items=orders %}

{#                <div class="pagination">#}
{#                    <div class="pagination-controls">#}
{#                        <a class="nav-item first num active" href="#">1</a>#}
{#                        <a class="nav-item num" href="#">2</a>#}
{#                        <a class="nav-item to-end" href="#">в конец</a>#}
{#                    </div>#}
{#                </div>#}
            <div class="cb"></div>
        </div>

        </div>

        <div class="cb"></div>


    {% endblock %}

templates/personal/profile_edit.html
{% extends 'base.html' %}

{% load flatpages_extras seo_extras services_extras order_extras catalog_extras %}

    {% block page-seo %}
        {% load seo_extras %}
        {% get_seo item %}
    {% endblock %}

    {% block header %}
        {% include "templatetags/header.html" with url="/profile/" %}
    {% endblock %}

    {% block breadcrumbs %}
        {% include "templatetags/breadcrumbs.html" %}
    {% endblock %}

    {% block main-content %}

        <div class="main-content" xmlns="http://www.w3.org/1999/html">
            <div class="cb" style="height: 10px;"></div>
            <div class="main-content-l lk">
                <div class="tree-menu side-menu">
                        <a class="menu-item lvl0 select" href="{% url 'personal:edit_user_profile' %}">
                            Личные данные
                        </a>
                        <a class="menu-item lvl0" href="{% url 'personal:list_orders' %}">
                            История покупок
                        </a>
                </div>
            </div>
            <form action="{% url 'personal:edit_user_profile' %}" method="post">
            {% csrf_token %}
            <div class="main-content-r tmce lk lk-top">
                <h1>Личные данные</h1>
                <table class="personal-info">
                    <tr>
                        <td class="field-caption">
                            ФИО
                        </td>
                        <td class="field {% if form.first_name.errors %}error{% endif %}">
                            {{ form.first_name }}
                            <span class="pencil"></span>
                        </td>
                    </tr>
                    <tr>
                        <td class="field-caption">
                            Телефон
                        </td>
                        <td class="field {% if profile_form.phone.errors %}error{% endif %}">
                            {{ profile_form.phone }}
                            <span class="pencil"></span>
                        </td>
                    </tr>
                    <tr>
                        <td class="field-caption">
                            E-mail
                        </td>
                        <td class="field">
                            <input placeholder="{{ email }}" required="" type="email" disabled="disabled">
                            <span class="pencil"></span>
                        </td>
                    </tr>
                    <tr>
                        <td class="field-caption">
                            Индекс
                        </td>
                        <td class="field {% if profile_form.address.errors %}error{% endif %}">
                            {{ profile_form.address }}
                            <span class="pencil"></span>
                        </td>
                    </tr>
                    <tr>
                        <td class="field-caption">
                            Город
                        </td>
                        <td class="field {% if profile_form.city.errors %}error{% endif %}">
                            {{ profile_form.city }}
                            <span class="pencil"></span>
                        </td>
                    </tr>
                    <tr>
                        <td class="field-caption">
                            Улица
                        </td>
                        <td class="field {% if profile_form.street.errors %}error{% endif %}">
                            {{ profile_form.street }}
                            <span class="pencil"></span>
                        </td>
                    </tr>
                    <tr>
                        <td class="field-caption">
                            Дом
                        </td>
                        <td class="field {% if profile_form.house.errors %}error{% endif %}">
                            {{ profile_form.house }}
                            <span class="pencil"></span>
                        </td>
                    </tr>
                    <tr>
                        <td class="field-caption">
                            Квартира
                        </td>
                        <td class="field  {% if profile_form.apartment.errors %}error{% endif %}">
                            {{ profile_form.apartment  }}
                            <span class="pencil"></span>
                        </td>
                    </tr>
                    <tr>
                        <td class="field-caption">
                        </td>
                        <td class="field">
                            <button class="cart-button">Сохранить</button>
                        </td>
                    </tr>
                </table>
            </div>
            </form>
            <div class="main-content-r tmce lk lk-bottom">
                <div class="fake-h1">Изменение пароля</div>
                <form action="{% url 'personal:edit_password' %}" method="post">
                    {% csrf_token %}
                <table class="personal-info">
                    <tr>
                        <td class="field-caption">
                            Старый пароль
                        </td>
                        <td class="field {% if novalid %}error{% endif %}">
                            <input name="oldpass" placeholder="" required="" type="password">
                            <span class="pencil"></span>
                        </td>
                    </tr>
                    <tr>
                        <td class="field-caption">
                            Новый пароль
                        </td>
                        <td class="field {% if norepeat %}error{% endif %}">
                            <input name="newpass" placeholder="" required="" type="password">
                            <span class="pencil"></span>
                        </td>
                    </tr>
                    <tr>
                        <td class="field-caption">
                            Подтвердите пароль
                        </td>
                        <td class="field  {% if norepeat %}error{% endif %}">
                            <input name="cnewpass" placeholder="" required="" type="password">
                            <span class="pencil"></span>
                        </td>
                    </tr>
                    <tr>
                        <td class="field-caption">
                        </td>
                        <td class="field">
                            <button class="cart-button">Изменить</button>
                        </td>
                    </tr>
                </table>
                </form>
            </div>

        </div>

        <div class="cb"></div>

    {% endblock %}