announce/urls.py
# -*- coding: utf-8 -*-

from django.conf.urls import patterns, url

urlpatterns = patterns('announce.views',
    url(r'^anonsy/$', 'announce_list', name='announce-list'),
    url(r'^anonsy/(?P<slug>([-\w]+))/$', 'announce_detail', name='announce-detail'),
)

feedback/urls.py
# -*- coding: utf-8 -*-

from django.conf.urls import patterns, url

urlpatterns = patterns('feedback.views',
    url(r'^kontakty/$', 'render_contacts', name='contacts'),
)

main/urls.py
# -*- coding: utf-8 -*-

from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.conf import settings
from django.views.generic.base import TemplateView

admin.autodiscover()

urlpatterns = patterns('',
    url(r'^$', TemplateView.as_view(template_name='index.html')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^profile/',include('personal.urls', namespace='personal')),
    url(r'^order/', include('order.urls',  namespace='order')),
    url(r'^dismiss_under_development_banner/$',
        'main.views.disable_under_development_banner',
        name="dismiss-under-development-banner"),
    url(r'^', include('feedback.urls')),
    url(r'^', include('announce.urls',  namespace='announce')),
    url(r'^', include('news.urls',  namespace='news')),
    url(r'^', include('services.urls',  namespace='services')),
)

if 'tinymce' in settings.INSTALLED_APPS:
    urlpatterns += patterns('',
        url(r'^tinymce/', include('tinymce.urls')),
    )

if 'filebrowser' in settings.INSTALLED_APPS:
    from filebrowser.sites import site
    urlpatterns += patterns('',
        url(r'^admin/filebrowser/', include(site.urls)),
    )

if 'grappelli' in settings.INSTALLED_APPS:
    urlpatterns += patterns('',
        url(r'^grappelli/', include('grappelli.urls')),
    )


if settings.DEBUG:
    from django.contrib.staticfiles.urls import staticfiles_urlpatterns
    urlpatterns += staticfiles_urlpatterns()
    urlpatterns += patterns('',
        url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {
            'document_root': settings.MEDIA_ROOT,
            }),
    )

urlpatterns += patterns('main.views',
    url(r'^change_theme/$', 'change_theme', name='change-theme'),
    url(r'^sitemap.xml$', 'sitemap_gen',),
)

urlpatterns += patterns('',
        url(r'^', include('catalog.urls',  namespace='catalog')),
        url(r'^', include('flatpages.urls', namespace='fpc')),
)

urlpatterns += patterns('quick_links.views',
    url(r'^(?P<slug>.*)$', 'link_detail', name='quick_link'),
)

personal/urls.py
# -*- coding: utf-8 -*-

from django.conf.urls import patterns, include, url

urlpatterns = patterns('personal.views',
    url(r'^login/$', 'login', name='auth_login'),
    url(r'^logout/$', 'logout',  name='auth_logout'),
    url(r'^changepass/$', 'edit_password', name='edit_password'),
    url(r'^password_reset/$', 'password_reset', name='password_reset'),
    url(r'^orders/$', 'list_orders', name='list_orders'),
    url(r'^$', 'edit_user_profile', name='edit_user_profile'),
    url(r'^reset/(?P<uidb36>[0-9A-Za-z]{1,13})/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        'password_reset_confirm',
        name='password_reset_confirm'),

    url(r'^', include('personal.backend.urls')),
)

feedback/models.py
# -*- coding: utf-8 -*- 

from django.db import models
from pyadmin import verbose_name_cases


class Feedback(models.Model):
    created_at = models.DateTimeField(verbose_name=u'Дата создания', auto_now_add=True)
    name = models.CharField(max_length=255, verbose_name=u'Имя', blank=True, null=True)
    phone = models.CharField(max_length=255, verbose_name=u'Контактный телефон', blank=True, null=True)
    email = models.EmailField(verbose_name=u'Электронная почта', blank=True, null=True)
    message = models.TextField(verbose_name=u'Сообщение')
    is_closed = models.BooleanField(verbose_name=u'Обработано', default=False)

    def __unicode__(self):
        return u'Сообщение №%s от %s' % (self.id, self.created_at)

    class Meta:
        verbose_name = verbose_name_cases(
            u'cooбщение с формы обратной связи', (u'cooбщение с формы обратной связи', u'cooбщения с формы обратной связи', u'cooбщений с формы обратной связи'),
            gender = 1, change = u'cooбщение с формы обратной связи', delete = u'cooбщение с формы обратной связи', add = u'cooбщение с формы обратной связи'
        )
        verbose_name_plural = verbose_name.plural
        ordering = ('-created_at',)

slider/models.py
# -*- coding: utf-8 -*-

from django.db import models
from pyadmin import verbose_name_cases
import os

class Slide(models.Model):
    name = models.CharField(max_length=255, verbose_name=u'Название')
    url = models.CharField(verbose_name=u'URL', blank=True, null=True,max_length=255, help_text=u"переход по указанной ссылке будет происходить при клике в любую точку слайда")
    content = models.TextField(verbose_name=u'Контент слайда',blank=True,null=True)
    image = models.ImageField(verbose_name=u'Изображение', blank=True, upload_to='uploads/slider/', help_text=u'Изображение .jpeg,jpg c размерами 750x303, изображение большего размера будет уменьшено и обрезано, изображение меньше указанного размера не будет изменено и будет выставлено по-центру слайда')
    order = models.SmallIntegerField(verbose_name=u'Порядок отображения', default=0)
    show = models.BooleanField(verbose_name=u'Отображать?',default=True)


    def __unicode__(self):
        return '%s' % self.name

    def got_image(self):
        try:
            if self.image:
                img_file = self.image.file
                if os.path.isfile(unicode(img_file)):
                    return True
        except:
            return False

    class Meta:
        verbose_name = verbose_name_cases(
            u'слайд', (u'Слайды', u'слайды', u'слайдов'),
            gender = 0, change = u'слайд', delete = u'слайд', add = u'слайд'
        )
        verbose_name_plural = verbose_name.plural
        ordering = ('order',)

feedback/forms.py
#-*- coding: utf-8 -*-

from django import forms
from django.core.exceptions import ValidationError
import re

class CustomForm(forms.Form):
    def __init__(self, *args, **kwargs):
        super(CustomForm, self).__init__(*args, **kwargs)
        for k, field in self.fields.items():
            if 'required' in field.error_messages:
                field.error_messages['required'] = u'Это поле обязательно!'
            if 'invalid' in field.error_messages:
                field.error_messages['invalid'] = u'Это поле заполнено неверно!'


def validate_phone(value):
    if not re.match("^((8|\+7)[\- ]?)?(\(?\d{3}\)?[\- ]?)?[\d\- ]{6,10}", value):
        raise ValidationError(u'%s не является правильным номером' % value)

def validate_email(value):
    if not re.match("^[_a-z0-9-]+(\.[_a-z0-9-]+)*@[a-z0-9-]+(\.[a-z0-9-]+)*(\.[a-z]{2,4})$", value):
        raise ValidationError(u'%s не является корректным email' % value)


class FeedbakForm(CustomForm):
    eman = forms.CharField(max_length=255,)
    email = forms.CharField(validators=[validate_email])
    message = forms.CharField(max_length=1000, )

feedback/views.py
# -*- coding: utf-8 -*-
from flatpages.models import FlatPage
from django.shortcuts import render

from forms import FeedbakForm
from message.models import Mail, Message
from models import Feedback
from constance import config
from django.core.mail import EmailMessage
from django.http import HttpResponse, HttpResponseRedirect
from django.template import Template, Context
from django.views.decorators.csrf import csrf_protect
from django.contrib.sites.models import Site
import json


def render_contacts(request):
    try:
        flatpage = FlatPage.objects.filter(type="contacts")[0]
        breadcrumbs = flatpage.get_breadcrumbs()
    except:
        pass

    context = feedback(request)
    if context:
        if request.is_ajax():
            return HttpResponse(json.dumps(context), mimetype="application/json")
        if context.get('success'):
            return HttpResponseRedirect(request.path+"?thanks_for_feedback=show")
    return render(request, 'flatpages/contacts.html', locals())


def feedback(request):
    if request.POST:

        post = request.POST
        context = ({})
        success = False

        if post.get('name') == 'imbot':
            form = FeedbakForm(request.POST)
            if form.is_valid():
                if 'eman' in form.cleaned_data:
                    context.update({"name":form.cleaned_data['eman']})
                if 'email' in form.cleaned_data:
                    context.update({"email":form.cleaned_data['email']})
                if 'message' in form.cleaned_data:
                    context.update({"message":form.cleaned_data['message']})

                mail_to = config.MANAGER_EMAIL.replace(' ', '').split(',')
                email_from = config.EMAIL_FROM.replace(' ', '').split(',')[0]
                domain = Site.objects.get_current().domain
                context.update({"SITE": domain})
                mail_to_client = []
                mail_to_client.append(context.get("email"))
                mail_subject = Mail.objects.filter(type="contacts_email")[0].subject
                mail_template = Mail.objects.filter(type="contacts_email")[0].mail
                mail_message = Template(mail_template).render(Context(context))
                mail = EmailMessage(mail_subject, mail_message, email_from, mail_to)
                mail.content_subtype='html'
                mail.send()
                mail_client = EmailMessage(mail_subject, mail_message, email_from, mail_to_client)
                mail_client.content_subtype = 'html'
                mail_client.send()

                feedback = Feedback()
                feedback.name = context.get("name")
                feedback.email = context.get("email")
                feedback.message = context.get("message")
                feedback.save()

                success = True
                respond = {"success": success,
                           "form_errors": '',
                           }
            else:
                respond = {"success": success,
                           "message": None,
                           "form_errors": form.errors,
                           }
            if request.is_ajax():
                mess = "<p>спасибо</p>"
                try:
                    mess = Message.objects.filter(type='message_after_feedback_form')[0].message
                except:
                    pass
                respond.update({"message": mess})
                return respond
            else:

                if 'eman' in request.POST:
                    context.update({"name": request.POST['eman']})
                if 'email' in request.POST:
                    context.update({"email": request.POST['email']})
                if 'message' in request.POST:
                    context.update({"message": request.POST['message']})
                context.update({"form": form,
                                "success": success,
                                })
                return context
    return None

templates/templatetags/announce_widget.html
{% if list %}
<div class="announce_widget">
    <div class="title">Анонсы</div>
    {% for item in list %}
        <div class="item">
            <a href="{{ item.get_absolute_url }}" class="">{{ item.get_title }}</a>
            <div class="short-desc">{{ item.teaser }}</div>
            <div class="date">{{ item.created_at }}</div>
        </div>
    {% endfor %}
    <a href="{% url "announce:announce-list" %}" class="all-announces small-gray-button">Все анонсы</a>
</div>
{% endif %}

templates/templatetags/auth_tag_old.html
{% load widget_tweaks %}
<div class="enter">
{% if data.no_enter %}
        <a class="enter-link" href="javascript:void(0)">Войти</a>
{% else %}
        <a class="enter-link" href="javascript:void(0)" >{{ name }}</a>
        <div class="enter-form">
        <p><a href="{% url 'personal:edit_user_profile' %}" class="cart-button">Личный кабинет</a>
        </p><p>
        <a href="{% url 'personal:auth_logout' %}" class="cart-button">Выйти</a></p>
        <div class="cb"></div>
        </div>

{% endif %}
</div>

{% if data.form %}
<div class="enter-form enter-form-reg" style="display: {{ data.hide }}">
    <div class="form-title">{{ data.name }}</div>
    <form enctype="" action='{{ data.action_to }}' method="post">
        {% csrf_token %}

        {% for field in data.form %}
            <label {% if field.errors %}class="error"{% endif %}>{{ field.label }}</label>
            {% with WIDGET_ERROR_CLASS='error' %}
                {% render_field field %}
            {% endwith %}
        {% endfor %}
        <div class="cb"></div>
        <button class="cart-button">{{ data.submit_name }}</button>
        <div class="cb"></div>
        {% for e in data.extra_links %}
            <p><a href="?{{ e.q }}=True">{{ e.name }}</a></p>
        {% endfor %}
    </form>
</div>
{% endif %}

templates/templatetags/footer111.html
{% load flatpages_extras placeholder catalog_extras %}
<footer>
    {% get_bottom_menu_old flatpage.url %}
    <div class="footer-wrap">
        <div class="cb-40"></div>
        {#  {% catalog_bottom_menu directory.slug %}#}
        {#  {% placeholder "phone" %}  #}
        {#  {% placeholder "address" %}  #}
        {#  <a href="mailto:{% placeholder "email" %}">{% placeholder "email" %}</a>  #}

        {% get_sub_bottom_menu_old %}

        <div class="footer-developers">
            <div class="copy">
                © {% now "Y" %} «МИР ТЮНИНГА»<br>
                сеть магазинов автотоваров
            </div>
            <div class="footer-social">
                {% include "templatetags/pluso.html" %}
            </div>
            <a class="footer-dev-logo" href="http://www.simplemedia.ru">
                <img src="/media/img/dev-logo.png">
            </a>
            <a href="http://www.simplemedia.ru/sozdanie-internet-magazina/">
                Создание интернет-магазина
            </a>
        </div>

        <div class="footer-sep"></div>

        <div class="footer-text tmce">
            <h5>Информация о ценах и наличии товара обновлена {% get_last_date %} UTC+7</h5>
            <p>
                Информация, указанная на сайте, не является публичной офертой. Информация о товарах, их технических свойствах и характеристиках, ценах является предложением “Мир Тюнинга” делать оферты. Акцептом “Мир Тюнинга” полученной оферты является подтверждение заказа с указанием товара и его цены. Сообщение “Мир Тюнинга” о цене заказанного товара, отличающейся от указанной в оферте, является отказом “Мир Тюнинга” от акцепта и одновременно офертой со стороны “Мир Тюнинга”. Информация о технических характеристиках товаров, указанная на сайте, может быть изменена производителем в одностороннем порядке. Изображения товаров на фотографиях, представленных в каталоге на сайте, могут отличаться от оригиналов. Информация о цене товара, указанная в каталоге на сайте, может отличаться от фактической к моменту оформления заказа на соответствующий товар. Подтверждением цены заказанного товара является сообщение “Мир Тюнинга” о цене такого товара.
            </p>
        </div>
        <div class="cb"></div>
    </div>
</footer>

templates/templatetags/jscss.html
{% load compress flatpages_extras %}
        <link href="http://cdn.simplemedia.ru/jquery-simple-image-gallery/simple_gallery.min.css" rel="stylesheet">
        <link href='http://fonts.googleapis.com/css?family=Roboto:400,300italic,300,100italic,100,400italic,500,500italic,700,700italic,900,900italic&subset=latin,cyrillic-ext' rel='stylesheet' type='text/css'>
    {% compress css %}
        <link rel="stylesheet" media="screen" href="/media/css/style.css" charset="utf-8">
    {% endcompress %}
{#    {% is_mobile request %}#}

    {% compress js %}
        <script type="text/javascript" src="/media/js/vendor/jquery-1.7.2.js"></script>
        <script type="text/javascript" src="/media/js/vendor/jquery.touchslider.js"></script>
        <script type="text/javascript" src="/media/js/vendor/masked_input.js"></script>
        <script type="text/javascript" src="/media/js/vendor/jquery-ui-1.8.23.custom.min.js" ></script>
        <script type="text/javascript" src="/media/js/vendor/jquery.ui.touch.js" ></script>
        <script type="text/javascript" src="/media/js/sticky_top_menu.js" ></script>
        <script type="text/javascript" src="/media/js/vendor/select2/select2.js" ></script>
        <script type="text/javascript" src="/media/js/vendor/select2/select_2_locale.ru.js" ></script>
        <script type="text/javascript" src="/media/js/input_delay.js"></script>
        <script type="text/javascript" src="/media/js/simpletabs.js"></script>
        <script type="text/javascript" src="/media/js/modals.js"></script>
        <script type="text/javascript" src="/media/js/forms.js"></script>
        <script type="text/javascript" src="/media/js/filter_widget.js"></script>
        <script type="text/javascript" src="/media/js/catalog_list_fix.js"></script>
        <script type="text/javascript" src="/media/js/vendor/jquery.validate.js"></script>
        <script type="text/javascript" src="/media/js/vendor/additional-methods.js"></script>
        <script type="text/javascript" src="/media/js/cart.js"></script>
    {% endcompress %}
        <script src="http://cdn.simplemedia.ru/jquery-simple-image-gallery/simple_gallery.min.js" type="text/javascript"></script>

templates/templatetags/pagination.html
<div class="pagination">
{% if items.paginator.page_range|length > 1 %}
    <div class="pagination-controls">
        {% if items.has_previous %}
            <a class="nav-item to-start" href="{{ page_url }}?{{ qs }}{{ filter_qs }}&page={{ items.previous_page_number }}">в начало</a>
        {% endif %}

        {% if items.range_page|first > 1 %}
            <a class="nav-item num first{% if items.number == 1 %} active{% endif %}" href ="{{ page_url }}?{{ qs }}{{ filter_qs }}&page=1">1</a>
        {% endif %}

        {% if items.range_page|first > 2 %}
            <span class="nav-item etc">...</span>
        {% endif %}

        {% for page_num in items.range_page %}
            <a class="nav-item{% if forloop.first%} first{% endif %} num{% if page_num == items.number %} active{% endif %}" href ="{{ page_url }}?{{ qs }}{{ filter_qs }}&page={{ page_num }}">{{ page_num }}</a>
        {% endfor %}

        {% if items.range_page|last < items.paginator.num_pages|add:"-1"  %}
            <span class="nav-item etc">...</span>
        {% endif %}

        {% if items.range_page|last < items.paginator.num_pages  %}
            <a class="nav-item num last{% if items.number == items.paginator.num_pages %} active{% endif %}" href ="{{ page_url }}?{{ qs }}{{ filter_qs }}&page={{ items.paginator.num_pages  }}" >{{ items.paginator.num_pages  }}</a>
        {% endif %}

        {% if items.has_next %}
            <a class="nav-item to-end" href ="{{ page_url }}?{{ qs }}{{ filter_qs }}&page={{ items.next_page_number }}">в конец</a>
        {% endif %}
    </div>
{% endif %}
</div>

templates/templatetags/pluso.html
<script type="text/javascript">(function() {
    if (window.pluso)if (typeof window.pluso.start == "function") return;
    if (window.ifpluso==undefined) { window.ifpluso = 1;
        var d = document, s = d.createElement('script'), g = 'getElementsByTagName';
        s.type = 'text/javascript'; s.charset='UTF-8'; s.async = true;
        s.src = ('https:' == window.location.protocol ? 'https' : 'http')  + '://share.pluso.ru/pluso-like.js';
        var h=d[g]('body')[0];
        h.appendChild(s);
    }})();</script>
<div class="pluso" data-background="transparent" data-options="medium,round,line,horizontal,nocounter,theme=04" data-services="vkontakte,facebook,twitter,odnoklassniki,google,moimir"></div>

templates/templatetags/side_2subcolmenu.html
{% load mptt_tags catalog_extras %}
{% if nodes %}
    <div class="submenu2">
        <ul>
            {% for x in nodes %}
                <li class="level1">
                    <a class="link1{% if x.slug == url %} active{% endif %}" href="{{ x.get_absolute_url }}">
                        {{ x.name|truncatechars:24 }}
                    </a>
                </li>
            {% endfor %}
        </ul>
    </div>
{% endif %}

templates/templatetags/side_2subcolmenuclass.html
{% if nodes %} class="level3"{% endif %}

templates/templatetags/side_menu.html
{% load mptt_tags %}
{% if nodes %}
    <div class="tree-menu side-menu">
        {% recursetree nodes %}
            <a class="menu-item{% if node.slug in expand %} expanded{% endif %}{% if node.slug == url %} active{% endif %}{% if not node.is_leaf_node %} wth-children{% endif %} lvl{{ node.level }}" href="{{ node.get_absolute_url }}">
                {{ node.get_menu_title }}
            </a>
            {% if not node.is_leaf_node %}
                {% if node.slug in expand %}{{ children }}{% endif %}
            {% endif %}
            {% if node.level == 0 %}
                {% if node.slug in expand %}<div class="menu-sep"></div>{% endif %}
            {% endif %}
        {% endrecursetree %}
    </div>
{% endif %}

templates/templatetags/side_menu_old.html
{% load mptt_tags %}
{% if nodes %}
    <div class="tree-menu side-menu">
        {% recursetree nodes %}
            <a class="menu-item{% if node.slug in expand %} expanded{% endif %}{% if node.slug == url %} active{% endif %}{% if not node.is_leaf_node %} wth-children{% endif %} lvl{{ node.level }}" href="{{ node.get_absolute_url }}">
                {{ node.get_menu_title }}
            </a>
            {% if not node.is_leaf_node %}
                {% if node.slug in expand %}{{ children }}{% endif %}
            {% endif %}
            {% if node.level == 0 %}
                {% if node.slug in expand %}<div class="menu-sep"></div>{% endif %}
            {% endif %}
        {% endrecursetree %}
    </div>
{% endif %}

templates/templatetags/text_ext.html
{% autoescape off %}{{ content }}{% endautoescape %}

templates/templatetags/top_menu.html
<div class="blc-menu">
    <div class="mobile_menu"><a href="javascript:void(0);">Меню</a></div>
	<ul>
        {% for node in nodes %}
            <li><a href="{{ node.url }}" class="top-menu-item{% if node.url == url %} active{% endif %}">{{ node.get_menu_title }}<span></span></a></li>
        {% endfor %}
	</ul>
</div>

templates/templatetags/top_menu_old.html
<div class="top-menu">
    {% for node in nodes %}
        <a href="{{ node.url }}" class="top-menu-item{% if node.url == url %} active{% endif %}">{{ node.get_menu_title }}</a>
    {% endfor %}
</div>

templates/templatetags/under_development.html
<div class="under-development">
    <p>
        Данный сайт Является демонстрационным. Продажи с него не осуществляются.
        <span class="button-handle">
            <a href="{% url "dismiss-under-development-banner" %}" class="close-it">×</a>
        </span>
    </p>
</div>