catalog/urls.py
# -*- coding: utf-8 -*-

from django.conf.urls.defaults import patterns, url
from django.views.generic.base import TemplateView

urlpatterns = patterns('catalog.views',
    url(r'^populyarnye-tovary/$', 'index_products', name='index-products'),
    url(r'^render_marker_data/(?P<id>\d+)/(?P<product_id>\d+)/$', 'render_marker_data', name='render-marker-data'),
    url(r'^all_(?P<type_promo>\w+)/$', 'list_promo_products', name='list_promo_products'),
    url(r'^analogi/(?P<id>[\d]+)/$', 'similar_products', name='simillar-products'),
    url(r'^(?P<slug>([-\w]+/){1,15})$', 'directory_detail_view', name='directory-detail'),
    url(r'^(?P<slug>([-\w]+/){1,15})(?P<item>[-\w]+)/$', 'product_detail_view', name='product-detail'),


)

main/urls.py
# -*- coding: utf-8 -*-

from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.conf import settings
from django.views.generic.base import TemplateView

admin.autodiscover()

urlpatterns = patterns('',
    url(r'^$', TemplateView.as_view(template_name='index.html')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^profile/',include('personal.urls', namespace='personal')),
    url(r'^order/', include('order.urls',  namespace='order')),
    url(r'^dismiss_under_development_banner/$',
        'main.views.disable_under_development_banner',
        name="dismiss-under-development-banner"),
    url(r'^', include('feedback.urls')),
    url(r'^', include('announce.urls',  namespace='announce')),
    url(r'^', include('news.urls',  namespace='news')),
    url(r'^', include('services.urls',  namespace='services')),
)

if 'tinymce' in settings.INSTALLED_APPS:
    urlpatterns += patterns('',
        url(r'^tinymce/', include('tinymce.urls')),
    )

if 'filebrowser' in settings.INSTALLED_APPS:
    from filebrowser.sites import site
    urlpatterns += patterns('',
        url(r'^admin/filebrowser/', include(site.urls)),
    )

if 'grappelli' in settings.INSTALLED_APPS:
    urlpatterns += patterns('',
        url(r'^grappelli/', include('grappelli.urls')),
    )


if settings.DEBUG:
    from django.contrib.staticfiles.urls import staticfiles_urlpatterns
    urlpatterns += staticfiles_urlpatterns()
    urlpatterns += patterns('',
        url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {
            'document_root': settings.MEDIA_ROOT,
            }),
    )

urlpatterns += patterns('main.views',
    url(r'^change_theme/$', 'change_theme', name='change-theme'),
    url(r'^sitemap.xml$', 'sitemap_gen',),
)

urlpatterns += patterns('',
        url(r'^', include('catalog.urls',  namespace='catalog')),
        url(r'^', include('flatpages.urls', namespace='fpc')),
)

urlpatterns += patterns('quick_links.views',
    url(r'^(?P<slug>.*)$', 'link_detail', name='quick_link'),
)

order/urls.py
# -*- coding: utf-8 -*-

from django.conf.urls import patterns, url

urlpatterns = patterns('order.views',
    url(r'^$', 'checkout', name='checkout'),
    url(r'^add/(?P<product_id>\d+)/$', 'add_to_cart', name='add_to_cart'),
    url(r'^remove/(?P<item_id>\d+)/$', 'remove_from_cart', name='remove_from_cart'),
    url(r'^update/(?P<item_id>\d+)/(?P<quantity>[\d-]+)', 'update_cart', name='update_cart'),
    # url(r'^clear/$', 'clear_cart', name='clear_cart'),
    url(r'^$', 'get_cart', name='cart'),
)

catalog/views.py
# -*- coding: utf-8 -*-
from constance import config
from django.core.urlresolvers import reverse_lazy
from django.db.models.query_utils import Q
from django.shortcuts import render, get_object_or_404
from django.http import Http404, HttpResponse
import json, re
from django.template.loader import render_to_string
from catalog.models import Directory, Product, Image, Promotion, Brand, Feature, FeatureValue, WebStockProduct, WebStock
from main.views import simple_pagination, get_products_per_page
from catalog.filter_widget import FilterWidget
import random
from datetime import date


def filter_by_features(request, products, filter_widget=None):
    directory_id_list = products.values_list("directory__id", flat=True)
    features = list(Feature.objects.filter(is_filter=True, group__directory__id__in=directory_id_list))
    products_ids = products.values_list("id", flat=True)

    param = None
    if request.method == 'GET':
        param = request.GET
    bypass_list_fader = []

    #отображение фильтра
    for f in features:
        name = '%s_%s' % (f.widget_type, f.id)
        featuresvalues = FeatureValue.objects.filter(feature__id=f.id, product__id__in=products_ids).order_by('value')
        if f.widget_type == 'fader_double':
            if featuresvalues:
                featuresvalues = list(featuresvalues)
                minvalue = featuresvalues[0].value
                current_min = minvalue
                maxvalue = featuresvalues[-1].value
                current_max = maxvalue
                if name+' min' in param:
                    try:
                        current_min = int(param.get(name+' min').replace(' ',''))
                    except:
                        pass
                if name+' max' in param:
                    try:
                        current_max = int(param.get(name+' max').replace(' ',''))
                    except:
                        pass

                fader_kwargs = {"name": name,
                                "type": "fader_double",
                                "label": f.name,
                                "order": f.order,
                                "min": minvalue,
                                "max": maxvalue,
                                "current_min":current_min,
                                "current_max":current_max}
                do_filter = filter_widget.update_feature(**fader_kwargs)
                if not do_filter:
                    bypass_list_fader.append(name+' min')
                    bypass_list_fader.append(name+' max')
        elif f.widget_type == 'select_box':
            if featuresvalues:
                selected_list = []
                if name in param:
                    selected_list = param.getlist(name)
                #Создаём список вариантов выбора
                list_for_out = []
                used_value = []
                for fv in list(featuresvalues):
                    if fv.value not in used_value:
                        used_value.append(fv.value)
                        list_for_out.append((fv.id,fv.value))
                fader_kwargs = { "name":name,
                                 "type":f.widget_type,
                                 "label":f.name,
                                 "order":f.order,
                                 "with_labels":True,  # нада добаить этот параметр, чтобы
                                 "values":list_for_out,  # Вот тут важен порядок!
                                 "selected_values":map(long, selected_list, )}
                filter_widget.update_feature(**fader_kwargs)

        elif f.widget_type == 'checkbox':
            selected = False
            if name in param:
                selected = True
            fader_kwargs = { "name":name,
                             "type":f.widget_type,
                             "label":f.name,
                             "order":f.order,
                             "checked":selected}
            filter_widget.update_feature(**fader_kwargs)
    if param:
        for parametr in param:
            if parametr not in bypass_list_fader:
                if parametr.startswith('checkbox_'):
                    feature_id = None
                    try:
                        feature_id = long(parametr[9:])
                    except:
                        pass
                    if feature_id:
                        products_ids = FeatureValue.objects.filter(feature__id=feature_id, product__id__in=products_ids).values_list('product__id',flat=True)

                elif parametr.startswith('select_box_'):
                    values = []
                    try:
                        for fvid in param.getlist(parametr):
                            try:
                                values.append(long(fvid))
                            except:
                                pass
                    except:
                        pass

                    if values:

                        full_values = FeatureValue.objects.filter(id__in = values).values_list('value', flat=True)
                        products_ids = FeatureValue.objects.filter(product__id__in=products_ids, value__in = full_values).values_list('product__id',flat=True)

                elif parametr.startswith('fader_double'):

                    pl = parametr.split(' ')
                    feature_id = None
                    try:
                        feature_id = long(pl[0][13:])
                    except:
                        pass
                    if feature_id:
                        if 'max' == pl[1]:
                            try:
                                products_ids = FeatureValue.objects.filter(feature__id=feature_id, product__id__in=products_ids,value__lte=int(param.get(parametr).replace(' ',''))).values_list('product__id',flat=True)
                            except:
                                pass
                        if 'min' == pl[1]:
                            try:
                                products_ids = FeatureValue.objects.filter(feature__id=feature_id, product__id__in=products_ids,value__gte=int(param.get(parametr).replace(' ',''))).values_list('product__id',flat=True)
                            except:
                                pass

    brands = list(products.order_by('brand__name').values_list('brand__id','brand__name'))

    list_for_out = []
    selected_list = []

    for bid, bnam in brands:
        if bid:
            if (bid, bnam) not in list_for_out:
                list_for_out.append((bid, bnam))

    if param.has_key('brand'):
        selected_list = param.getlist('brand')

    if len(list_for_out) > 0:

        filter_widget.update_feature(name=u'brand',
                                     type='select_box',
                                     label=u'Брэнд',
                                     order=99,
                                     with_labels=True,  # нада добаить этот параметр, чтобы
                                     values=list_for_out,  # Вот тут важен порядок!
                                     selected_values=map(long, selected_list, )
        )

    prices = list(products.order_by('price').values_list('price',flat=True))
    minvalue = int(prices[0])
    maxvalue = int(prices[-1])
    selected_min_price = minvalue
    selected_max_price = maxvalue

    price_kwargs = {"name": "price",
                  "type": "fader_double",
                  "label": u"Цена",
                  "order": 100,
                  "min": minvalue,
                  "max": maxvalue}

    if param.has_key('price min'):
        try:
            selected_min_price = int(param.get('price min').replace(" ",""))
            price_kwargs.update({"current_min": selected_min_price})
        except:
            pass

    if param.has_key('price max'):
        try:
            selected_max_price = int(param.get('price max').replace(" ",""))
            price_kwargs.update({"current_max": selected_max_price })
        except:
            pass

    filter_widget.update_feature(**price_kwargs)

    if products_ids:
        if selected_list:
            products = products.filter(id__in=products_ids,price__gte=selected_min_price,price__lte=selected_max_price,brand__id__in=selected_list)
        else:
            products = products.filter(id__in=products_ids,price__gte=selected_min_price,price__lte=selected_max_price)
    else:
        products = []
    return products, filter_widget


def filter_by_order(request, products):
    #get a data for ordering
    try:
        sort = request.POST['sort']
    except:
        try:
            sort = request.GET['sort']
        except:
            sort = None
    if sort == 'price':
        products = products.order_by('price')
    elif sort == 'price_desc':
        products = products.order_by('-price')

    return products, sort


# из url вида /some/url/here/ берем "here" - т.е. последний слаг
def get_exact_directory(string):
    directories_slug = re.split('/', string)
    directory = None
    for slug in directories_slug[:-1]:
        directory = Directory.objects.get(directory=directory, slug=slug)
    return directory


# раздел
def directory_detail_view(request, slug):
    # TODO: создание контейнера для вывода товаров
    # https://simplemedia.atlassian.net/browse/MEZON-69
    try:
        directory = get_exact_directory(slug)
    except Directory.DoesNotExist:
        # ***
        # костыль, йопт!  разбиираем урл на урл раздела и слаг товара
        # например /razdel/eshe_razdel/tovar/ =>
        #   slug : /razdel/eshe_razdel/
        #   item :                     tovar
        # ***
        grups = re.search("^(?P<slug>[\w/-]+)/(?P<item>[-\w]+)/$", slug)
        if grups:
            slug = grups.group("slug") + "/"
            item = grups.group("item")
            return product_detail_view(request, slug, item)
        else:
            raise Http404

    context = {
        'directory': directory,

templates/catalog/tags/accessories_and_similar_products.html
<div>
    {% if acc_groups %}
    <h2>Аксессуары</h2>
    {% endif %}
    <a href="{{ similar_products_link }}">Аналогичные товары</a>
</div>
<div class="cb"></div>

{#TODO: вывод групп аксессуаров#}
{% if acc_groups %}

{% endif %}

templates/catalog/tags/bottom_menu.html
{% if nodes %}
    <div class="catalog-popular">
        <div class="taitle">Популярные категории</div>
        {% for node in nodes %}
            <a href="{{ node.get_absolute_url }}" class="bottom-menu-item{% if node.slug == url %} active{% endif %}">{{ node.get_menu_title }}</a>
        {% endfor %}
        <div class="cb"></div>
    </div>
{% endif %}

templates/catalog/tags/items_list.html
<div style="overflow: hidden; padding: 0 0 50px 0;">
    {% if items %}

        {% for item in items %}
            {% include "catalog/tags/product.html" %}
            {% if forloop.counter|divisibleby:4 %}

            {% endif %}
        {% endfor %}

    {% endif %}
</div>

templates/catalog/tags/items_list_old.html
{% if items %}
    <div class="catalog-items-list">
        {% for item in items %}
            {% if forloop.first %}<div class="items-list-row">{% endif %}
                {% include "catalog/tags/product_old.html" %}
            {% if forloop.counter|divisibleby:4 %}</div>
                {% if not forloop.last %}<div class="items-list-row">{% endif %}
            {% endif %}
        {% endfor %}
        {% if not items|length|divisibleby:4 %}</div>{% endif %}
    </div>
    <div class="cb"></div>
{% endif %}

templates/catalog/tags/list_controls.html
<div class="list-controls">
    <div class="list-sort">
        <div class="sort-name">

            Сортировать по <span class="select-sort">
            {% if not sort_is or sort_is == "price" %}<span>цене</span> ▲{% endif %}
            {% if sort_is == "price_desc" %}<span>цене</span> ▼{% endif %}
            </span>
            <div class="sort-menu">
                <a href="{{ directory.get_absolute_url }}?sort=price{{ filter_qs }}">по возрастанию цены</a>
                <a href="{{ directory.get_absolute_url }}?sort=price_desc{{ filter_qs }}">по убыванию цены</a>
            </div>
        </div>
    </div>
    <div class="list-per-page">
        <span>Показывать по  </span>
        <a href="{{ directory.get_absolute_url }}?per_page=25{{ per_page_qs }}{{ filter_qs }}" class="num {% if per_page == "25" %}active{% endif %} first">25</a>
        <a href="{{ directory.get_absolute_url }}?per_page=50{{ per_page_qs }}{{ filter_qs }}" class="num {% if per_page == "50" %}active{% endif %}">50</a>
        <a href="{{ directory.get_absolute_url }}?per_page=75{{ per_page_qs }}{{ filter_qs }}" class="num {% if per_page == "75" %}active{% endif %}">75</a>
        <a href="{{ directory.get_absolute_url }}?per_page=100{{ per_page_qs }}{{ filter_qs }}" class="num {% if per_page == "100" %}active{% endif %}">100</a>
        {% if per_page != "show_all" %}
            <a href="{{ directory.get_absolute_url }}?per_page=show_all{{ per_page_qs }}{{ filter_qs }}" class="show-all">показать всё</a>
        {% endif %}
    </div>
    <div class="cb"></div>
</div>

templates/catalog/tags/list_controls_old.html
<div class="list-controls">
    <div class="list-sort">
        <div class="sort-name">

            Сортировать по <span class="select-sort">
            {% if not sort_is or sort_is == "price" %}<span>цене</span> ▲{% endif %}
            {% if sort_is == "price_desc" %}<span>цене</span> ▼{% endif %}
            </span>
            <div class="sort-menu">
                <a href="{{ directory.get_absolute_url }}?sort=price{{ filter_qs }}">по возрастанию цены</a>
                <a href="{{ directory.get_absolute_url }}?sort=price_desc{{ filter_qs }}">по убыванию цены</a>
            </div>
        </div>
    </div>
    <div class="list-per-page">
        <span>Показывать по  </span>
        <a href="{{ directory.get_absolute_url }}?per_page=25{{ per_page_qs }}{{ filter_qs }}" class="num {% if per_page == "25" %}active{% endif %} first">25</a>
        <a href="{{ directory.get_absolute_url }}?per_page=50{{ per_page_qs }}{{ filter_qs }}" class="num {% if per_page == "50" %}active{% endif %}">50</a>
        <a href="{{ directory.get_absolute_url }}?per_page=75{{ per_page_qs }}{{ filter_qs }}" class="num {% if per_page == "75" %}active{% endif %}">75</a>
        <a href="{{ directory.get_absolute_url }}?per_page=100{{ per_page_qs }}{{ filter_qs }}" class="num {% if per_page == "100" %}active{% endif %}">100</a>
        {% if per_page != "show_all" %}
            <a href="{{ directory.get_absolute_url }}?per_page=show_all{{ per_page_qs }}{{ filter_qs }}" class="show-all">показать всё</a>
        {% endif %}
    </div>
    <div class="cb"></div>
</div>

templates/catalog/tags/mainpage_sale.html
{% load thumbnail watermark %}

{% if nodes %}
             <div class="blc-conteiner mainlistgoods">
				<div class="blc-goods">                    
				 	<div class="allgoods" style="display: none"><a href="#">Все по супер цене</a></div>
				 	<div class="header">Супер цена</div>
                    {% for x in nodes %}
                        <div class="row">
                            <div class="foto"><a href="{{ x.product.get_absolute_url }}">
                                {% if x.product.get_primary_image %}
                                    {% if x.product.get_primary_image.file.height %}
                                        {% thumbnail x.product.get_primary_image.file "x113" as im %}
                                            <img src="{{ im.url }}" alt="" />
                                        {% endthumbnail %}
                                    {% else %}
                                        {% thumbnail x.product.get_primary_image.file "113" as im %}
                                            <img src="{{ im.url }}" alt="" />
                                        {% endthumbnail %}
                                    {% endif %}
                                {% else %}
                                    <img src="http://placehold.it/113x113" alt="{{ item.name }}">
                                {% endif %}
                            </a></div>
                            <div class="descr">
                                <div class="name"><a href="{{ x.product.get_absolute_url }}">{{ x.product.name|truncatechars:'50' }}</a></div>
                                <div class="price">{{ x.product.price|floatformat }} руб.</div>
                            </div>
                        </div>
                    {% endfor %}
				</div>
			</div>
{% endif %}

templates/catalog/tags/product.html
{% load thumbnail watermark %}

<div class="row">
    <div class="foto">
        <a class="product-link" href="{{ item.get_absolute_url }}" title="{{ item.name }}">
                {% if item.get_primary_image %}
                    {% if item.get_primary_image.file|is_portrait %}
                        {% thumbnail item.get_primary_image.file "x113" crop="center" upscale=False quality=100 as im %}
                            <img src="{{ im.url }}" alt="{{ item.name }}">
                        {% endthumbnail %}
                    {% else %}
                        {% thumbnail item.get_primary_image.file "113" crop="center" upscale=False quality=100 as im %}
                            <img src="{{ im.url }}" alt="{{ item.name }}">
                        {% endthumbnail %}
                    {% endif %}
                {% else %}
                    <img src="http://placehold.it/113x113" alt="{{ item.name }}">
                {% endif %}
        </a>
    </div>
    <div class="descr">
		<div class="name">
            <a class="product-link" href="{{ item.get_absolute_url }}" title="{{ item.name }}">{{ item.name|truncatechars:'50' }} {% if item.brand %}{{ item.brand }}{% endif %}</a>
		</div>
		<div class="price">{{ item.price|floatformat }} руб.</div>

        <div class="product-short-desc tmce" style="display: none">
            {% if item.short_description %}
                {% autoescape off %}{{ item.short_description|linebreaksbr|truncatechars:55 }}{% endautoescape %}
            {% endif %}
        </div>

        <form style="display: none" class="catalog-product-form" action="{% url "order:add_to_cart" item.id %}" method="post">
            <div class="product-price">
                {% if item.get_price %}{{ item.get_price }} руб.{% endif %}
            </div>

            {% csrf_token %}
            <input type="hidden" name="quantity" value="1">
            <button class="small-butt buy-product" type="submit">Купить</button>
        </form>
	</div>
</div>

templates/catalog/tags/product_images_slider.html
{% if sets %}
{% load thumbnail watermark %}
<div class="product_images_slider">
    <div class="product_images_slider-viewport">
        <div>
            {% for set in sets %}
                <div class="product_images_slider-item">
                    {% for img in set %}
                        <a rel="group" href="{{ img.file.url|watermark:"WM,position=br,opacity=100" }}" class="sgallery {% cycle "first" "" "last" %}" title="{{ img.name }}">
                            {% thumbnail img.file "80x60" crop="center" upscale=False quality=100 as im %}
                                <img src="{{ im.url }}" alt="{{ img.name }}">
                            {% endthumbnail %}
                        </a>
                    {% endfor %}
                </div>
            {% endfor %}
        </div>
    </div>

    <span class="product_images_slider-prev"></span>

    <span class="product_images_slider-next"></span>

    <script>jQuery(function($){$(".product_images_slider").touchSlider({autoplay: false, namespace: "product_images_slider"});});</script>
</div>
{% endif %}

templates/catalog/tags/product_old.html
{% load thumbnail watermark %}
<div  class="catalog-product {% if forloop.counter|divisibleby:4 %}last{% endif %}">
    <a class="product-link" href="{{ item.get_absolute_url }}" title="{{ item.name }}">
        <div class="product-image-wrapper">
            <div class="product-image">
                {% if item.get_primary_image %}
                    {% if item.get_primary_image.file|is_portrait %}
                        {% thumbnail item.get_primary_image.file "x121" crop="center" upscale=False quality=100 as im %}
                            <img src="{{ im.url }}" alt="{{ item.name }}">
                        {% endthumbnail %}
                    {% else %}
                        {% thumbnail item.get_primary_image.file "160" crop="center" upscale=False quality=100 as im %}
                            <img src="{{ im.url }}" alt="{{ item.name }}">
                        {% endthumbnail %}
                    {% endif %}
                {% else %}
                    <img src="http://placehold.it/165x112" alt="{{ item.name }}">
                {% endif %}
            </div>
        </div>

        <div class="product-title">
            {{ item.name }} {% if item.brand %}{{ item.brand }}{% endif %}
        </div>
    </a>

        <div class="product-short-desc tmce">
            {% if item.short_description %}
                {% autoescape off %}{{ item.short_description|linebreaksbr|truncatechars:55 }}{% endautoescape %}
            {% endif %}
        </div>

    <form class="catalog-product-form" action="{% url "order:add_to_cart" item.id %}" method="post">
        <div class="product-price">
            {% if item.get_price %}{{ item.get_price }} руб.{% endif %}
        </div>

        {% csrf_token %}
        <input type="hidden" name="quantity" value="1">
        <button class="small-butt buy-product" type="submit">Купить</button>
    </form>
</div>

templates/catalog/tags/product_set.html
{% if product_set %}
<div class="products-set">
    <h2>
        <a class="catalog-subdir-link" href="{{ product_set.get_absolute_url }}" title="{{ product_set.name }}">
            {{ taitle }}
{#        {% if product_set.preview_products_count > 4 %}#}
{#            <span>{{ product_set.preview_products_count }}</span>#}
{#        {% endif %}#}
        </a>

        {% if product_set.preview_products_count > 4 %}
            <span style="font-size: 14px;"> / <a href="{{ product_set.get_absolute_url }}" class="small-gray-button show-all-products" >Все товары</a></span>
        {% endif %}
    </h2>

        {% if product_set.top_description %}
            {% autoescape off %}{{ product_set.top_description }}{% endautoescape %}
        {% endif %}

    {% include "catalog/tags/items_list.html" with items=product_set.preview_products %}

</div>
{% endif %}

templates/catalog/tags/product_set_old.html
{% if product_set %}
<div class="products-set">
    <a class="catalog-subdir-link" href="{{ product_set.get_absolute_url }}" title="{{ product_set.name }}">
        <h2>{{ taitle }}</h2>
{#        {% if product_set.preview_products_count > 4 %}#}
{#            <span>{{ product_set.preview_products_count }}</span>#}
{#        {% endif %}#}
    </a>
    {% if product_set.preview_products_count > 4 %}
        <a href="{{ product_set.get_absolute_url }}" class="small-gray-button show-all-products" >Все товары</a>
    {% endif %}
    <div class="cb-20"></div>
        {% if product_set.top_description %}
            {% autoescape off %}{{ product_set.top_description }}{% endautoescape %}
        {% endif %}
    <div class="cb"></div>
    {% include "catalog/tags/items_list_old.html" with items=product_set.preview_products %}
</div>
{% endif %}

templates/catalog/tags/products_promotion_slider.html
{% if product_sets %}
    <div class="product-promotion-slider">
        <br /><br />
        <div class="tab-switches">
            {% for set in product_sets %}
                <div class="promo-tab {% if forloop.first %}active first{% endif %}{% if forloop.last %} last{% endif %}"><h2>{{ set.taitle }}</h2></div>
            {% endfor %}
        </div>
        {% for set in product_sets %}
            {% with tab_id=forloop.counter0 %}
            <div class="product_slider tab_id{{ tab_id }} {% if forloop.first %}active{% endif %}">
                <div class="product_slider-viewport tab_id{{ tab_id }}">
                    <div class="blc-goods">
                        {% for page in set.pages %}
                            <div class="product_slider-item tab_id{{ tab_id }}">
                                {% include "catalog/tags/items_list.html" with items=page %}
                            </div>
                        {% endfor %}
                    </div>
                </div>
                {% if set.has_pages %}
                    <span class="product_slider-prev tab_id{{ tab_id }}"></span>
                    <span class="product_slider-next tab_id{{ tab_id }}"></span>
                {% endif %}
            </div>
            {% endwith %}
        {% endfor %}
    </div>
{% endif %}

templates/catalog/tags/products_promotion_slider_old.html
{% if product_sets %}
    <div class="product-promotion-slider">
        <div class="tab-switches">
            {% for set in product_sets %}
                <div class="promo-tab {% if forloop.first %}active first{% endif %}{% if forloop.last %} last{% endif %}">{{ set.taitle }}</div>
            {% endfor %}
        </div>
        {% for set in product_sets %}
            {% with tab_id=forloop.counter0 %}
            <div class="product_slider tab_id{{ tab_id }} {% if forloop.first %}active{% endif %}">
                <div class="product_slider-viewport tab_id{{ tab_id }}">
                    <div>
                        {% for page in set.pages %}
                            <div class="product_slider-item tab_id{{ tab_id }}">
                                {% include "catalog/tags/items_list_old.html" with items=page %}
                            </div>
                        {% endfor %}
                    </div>
                </div>
                {% if set.has_pages %}
                    <span class="product_slider-prev tab_id{{ tab_id }}"></span>
                    <span class="product_slider-next tab_id{{ tab_id }}"></span>
                {% endif %}
                <script>jQuery(function($) {
                    $(".product_slider.tab_id{{ tab_id }}").touchSlider({autoplay: true,
                                                                        namespace: "product_slider",
                                                                        x_namespace: ".tab_id{{ tab_id }}"});

                });
                </script>
            </div>
            {% endwith %}
        {% endfor %}
    </div>

    <script type="text/javascript">
        jQuery(function($) {
            simple_tabs($(".product_slider"),$(".promo-tab"));
        });
    </script>
{% endif %}