main/urls.py
# -*- coding: utf-8 -*-

from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.conf import settings
from django.views.generic.base import TemplateView

admin.autodiscover()

urlpatterns = patterns('',
    url(r'^$', TemplateView.as_view(template_name='index.html')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^profile/',include('personal.urls', namespace='personal')),
    url(r'^order/', include('order.urls',  namespace='order')),
    url(r'^dismiss_under_development_banner/$',
        'main.views.disable_under_development_banner',
        name="dismiss-under-development-banner"),
    url(r'^', include('feedback.urls')),
    url(r'^', include('announce.urls',  namespace='announce')),
    url(r'^', include('news.urls',  namespace='news')),
    url(r'^', include('services.urls',  namespace='services')),
)

if 'tinymce' in settings.INSTALLED_APPS:
    urlpatterns += patterns('',
        url(r'^tinymce/', include('tinymce.urls')),
    )

if 'filebrowser' in settings.INSTALLED_APPS:
    from filebrowser.sites import site
    urlpatterns += patterns('',
        url(r'^admin/filebrowser/', include(site.urls)),
    )

if 'grappelli' in settings.INSTALLED_APPS:
    urlpatterns += patterns('',
        url(r'^grappelli/', include('grappelli.urls')),
    )


if settings.DEBUG:
    from django.contrib.staticfiles.urls import staticfiles_urlpatterns
    urlpatterns += staticfiles_urlpatterns()
    urlpatterns += patterns('',
        url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {
            'document_root': settings.MEDIA_ROOT,
            }),
    )

urlpatterns += patterns('main.views',
    url(r'^change_theme/$', 'change_theme', name='change-theme'),
    url(r'^sitemap.xml$', 'sitemap_gen',),
)

urlpatterns += patterns('',
        url(r'^', include('catalog.urls',  namespace='catalog')),
        url(r'^', include('flatpages.urls', namespace='fpc')),
)

urlpatterns += patterns('quick_links.views',
    url(r'^(?P<slug>.*)$', 'link_detail', name='quick_link'),
)

order/urls.py
# -*- coding: utf-8 -*-

from django.conf.urls import patterns, url

urlpatterns = patterns('order.views',
    url(r'^$', 'checkout', name='checkout'),
    url(r'^add/(?P<product_id>\d+)/$', 'add_to_cart', name='add_to_cart'),
    url(r'^remove/(?P<item_id>\d+)/$', 'remove_from_cart', name='remove_from_cart'),
    url(r'^update/(?P<item_id>\d+)/(?P<quantity>[\d-]+)', 'update_cart', name='update_cart'),
    # url(r'^clear/$', 'clear_cart', name='clear_cart'),
    url(r'^$', 'get_cart', name='cart'),
)

order/models.py
# -*- coding: utf-8 -*-
from decimal import Decimal

from catalog.models import Product, WebStock
from django.contrib.contenttypes.models import ContentType, ContentTypeManager
from django.db import models
from django.db.models import permalink

from catalog.templatetags.catalog_filters import format_price
from pyadmin import verbose_name_cases


class Cart(models.Model):
    created_at = models.DateTimeField(verbose_name=u'Дата создания')
    is_checked_out = models.BooleanField(verbose_name=u'Заказ сформирован', default=False)

    class Meta:
        verbose_name = verbose_name_cases(
            u'корзина', (u'корзины', u'корзины', u'корзины'),
            gender = 0, change = u'корзину', delete = u'корзину', add = u'корзину'
        )
        verbose_name_plural = verbose_name.plural
        ordering = ('-created_at',)


    def __unicode__(self):
        return unicode(self.created_at)


class CartItemManager(models.Manager):
    def get(self, *args, **kwargs):
        if 'item' in kwargs:
            kwargs['content_type'] = ContentType.objects.get_for_model(type(kwargs['item']))
            kwargs['object_id'] = kwargs['item'].pk
            del(kwargs['item'])
        return super(CartItemManager, self).get(*args, **kwargs)

class CartItem(models.Model):
    cart = models.ForeignKey(Cart, verbose_name=u'Корзина')
    price = models.DecimalField(max_digits=18, decimal_places=2, verbose_name=u'Стоимость единицы товара')
    quantity = models.PositiveIntegerField(verbose_name=u'Количество', default=1)

    content_type = models.ForeignKey(ContentType)
    object_id = models.PositiveIntegerField()

    objects = ContentTypeManager()

    class Meta:
        verbose_name = verbose_name_cases(
            u'элемент корзины', (u'Элементы корзины', u'элементы корзины', u'элементов корзины'),
            gender=2, change=u'элемент корзины', delete=u'элемент корзины', add=u'элемент корзины'
        )
        verbose_name_plural = verbose_name.plural
        ordering = ('cart',)


    def __unicode__(self):
        return ''

    def total_price(self):
        return self.quantity * float(self.price)
    total_price = property(total_price)

    def get_item(self):
        return self.content_type.get_object_for_this_type(id=self.object_id)

    def set_item(self, product):
        self.content_type = ContentType.objects.get_for_model(type(product))
        self.object_id = product.pk

    product = property(get_item, set_item)


class OrderStatus(models.Model):
    name = models.CharField(verbose_name=u'Название', max_length=255)
    is_initial = models.BooleanField(verbose_name=u'Начальный', default=False)
    is_closing = models.BooleanField(verbose_name=u'Конечный', default=False)
    index_number = models.IntegerField(verbose_name=u'Порядок статуса',default=0)

    def __unicode__(self):
        return self.name

    class Meta:
        verbose_name = verbose_name_cases(
            u'статус заказа', (u'статус заказа', u'статус заказа', u'статус заказа'),
            gender=2, change=u'Статусы заказов', delete=u'Статусы заказов', add=u'Статусы заказов'
        )
        verbose_name_plural = verbose_name.plural


PAYMENT_TYPE = (
    ('cash_payment', u'Наличными, оплата картой в магазине.'),
    ('non_cash_payment', u'Безналичный расчет'),
)

DELIVERY_TYPE = (
    ('self_delivery', u'Самовывоз'),
    ('delivery', u'Доставка'),
)

class Order(models.Model):
    created_at = models.DateTimeField(verbose_name=u'Дата оформления', auto_now_add=True)

    # Данные пок#упател
    full_name = models.CharField(verbose_name=u'Ф.И.О.', max_length=255, blank=True, null=True,)
    # first_name = models.CharField(verbose_name=u'Имя', max_length=255)
    # last_name = models.CharField(verbose_name=u'Фамилия', max_length=255, blank=True, null=True)

    # addition_phone = models.CharField(verbose_name=u'Доп. телефон', max_length=255, blank=True, null=True)


    # Комментарии к заказу


    # Доставка заказа
    delivery_type = models.CharField(verbose_name=u'Способ доставки', max_length=255, choices=DELIVERY_TYPE, blank=True, null=True)
    # region  = models.CharField(verbose_name=u"Регион", max_length=255, blank=True, null=True)

    city = models.CharField(verbose_name=u"Город", max_length=255, blank=True, null=True)
    postal_code = models.CharField(verbose_name=u"Индекс", max_length=255, blank=True, null=True)
    address = models.CharField(verbose_name=u"Адрес", max_length=500, blank=True, null=True)
    phone = models.CharField(verbose_name=u'Телефон', max_length=255, )
    email = models.EmailField(verbose_name=u'E-mail', blank=True, null=True)
    comment = models.TextField(verbose_name=u'Комментарий к заказу', blank=True)

    street = models.CharField(verbose_name=u'Улица', max_length=255, blank=True, null=True)
    house = models.CharField(verbose_name=u'Дом', max_length=255, blank=True, null=True)
    # building = models.CharField(verbose_name=u'Корпус', max_length=255, blank=True, null=True)
    apartment = models.CharField(verbose_name=u'Квартира', max_length=255, blank=True, null=True)

    # Оплата заказа
    payment_type = models.CharField(verbose_name=u'Способ оплаты', max_length=255, choices=PAYMENT_TYPE, default='cash_payment')

    status = models.ForeignKey(OrderStatus, verbose_name=u'Статус', blank=True, null=True)

    webstock = models.ForeignKey(WebStock, verbose_name=u'Склад',blank=True, null=True)

    class Meta:
        verbose_name = verbose_name_cases(
            u'заказ', (u'Заказ', u'Заказ', u'Заказ'),
            gender=2, change=u'Заказ', delete=u'Заказ', add=u'Заказ'
        )
        verbose_name_plural = verbose_name.plural
        ordering = ('-created_at',)

    def get_items(self):
        return list(OrderItem.objects.filter(order=self))

    def __unicode__(self):
        return u'Заказ №%s от %s' % (self.id, self.created_at)


class OrderItem(models.Model):
    order = models.ForeignKey(Order, verbose_name=u'Заказ')
    product = models.ForeignKey(Product, verbose_name=u'Товар', on_delete=models.SET_NULL, null=True)
    price = models.DecimalField(verbose_name=u'Стоимость единицы товара', max_digits=18, decimal_places=2, help_text=u'Стоимость на момент заказа')
    quantity = models.DecimalField(verbose_name=u'Количество', max_digits=18, decimal_places=6)

    #save product name in case it would be delete by carefree admin
    product_name = models.CharField(verbose_name=u'Наименование товара', max_length=255, blank=True, null=True)

    class Meta:
        verbose_name = verbose_name_cases(
            u'элемент заказа', (u'Элементы заказов', u'Элементы заказов', u'Элементы заказов'),
            gender=2, change=u'элемент заказов', delete=u'элемент заказов', add=u'элемент заказов'
        )
        verbose_name_plural = verbose_name.plural

    def p_sum(self):
        return format_price(Decimal(float(self.price)*float(self.quantity)))

    def p_quantity(self):
        return format_price(self.quantity)

    def get_absolute_url(self):
        return self.product.get_absolute_url()
    # @permalink
    # def get_absolute_url(self):
    #     if self.product.directory.old_slug:
    #         url = "%s/" % self.product.directory.old_slug
    #     else:
    #         url = "%s/" % self.product.directory.slug
    #         page = self.product.directory
    #         while page.directory:
    #             url = "%(sl)s/%(prev)s" % {"prev": url, "sl": page.directory.slug}
    #             page = page.directory

        return 'product-detail', (), {'slug': url, 'item':self.product.slug}
#        return 'product-detail', (), {'pk': self.product.pk}

    def save(self, *args, **kwargs):
        if not self.product_name and self.product:
            self.product_name = self.product.name
        super(OrderItem, self).save(*args, **kwargs)

    def __unicode__(self):
        return u'Позиция заказа №%s. Наименование: %s, Количество: %s, Стоимость единицы: %s' % (self.order.id, self.product_name, self.quantity, self.price)

order/forms.py
# -*- coding: utf-8 -*-

from order.models import Order, PAYMENT_TYPE
from django import forms


class OrderForm(forms.ModelForm):
    # payment_type = forms.ChoiceField(label=u'Способ оплаты', choices=PAYMENT_TYPE)
    class Meta:
        model = Order
        exclude = ('status', 'created_at')

    def __init__(self, *args, **kwargs):
        super(OrderForm, self).__init__(*args, **kwargs)
        for field in self.fields:
            self.fields[field].widget.attrs['placeholder'] = self.fields[field].label

order/views.py
# -*- coding: utf-8 -*-

import json
from django.contrib import messages
from catalog.models import Product
from message.models import Mail
from order.cart import ShoppingCart
from order.forms import OrderForm
from order.models import Order, OrderItem, OrderStatus, CartItem
from constance import config
from django.core.mail import EmailMessage
from django.core.mail import send_mail
from django.core.validators import email_re
from django.http import HttpResponseRedirect, HttpResponse
from django.shortcuts import render
from django.template import Context, Template
from django.template.loader import render_to_string


def get_email_list(var):
    addresses = var.replace(' ', '').split(',')
    valid_emails = []
    for email in addresses:
        if bool(email_re.match(email)):
            valid_emails.append(email)
    return valid_emails


def customer_email(request, order):
    context = {
        'order':order,
        }

    if order.email:
        email_list = get_email_list(order.email)
        try:
            subject = Mail.objects.get(type='customer_email').subject
            html_content = Template(Mail.objects.get(type='customer_email').mail).render(Context(context))
            msg = EmailMessage(subject, html_content, config.ORDER_FROM_EMAIL, email_list)
            msg.content_subtype = "html"
            msg.send()
        except Exception, e:
            text = 'Ошибка %s'%e
            subject = 'покупка'
            html_content = render_to_string('text.html',{'context': text})
            msg = EmailMessage(subject, html_content, config.ORDER_FROM_EMAIL, email_list)
            msg.content_subtype = "html"
            msg.send()


def seller_email(request, order):
    email_list = get_email_list(config.ORDER_TO_EMAIL)
    try:
        context = {
            'order':order,
            }

        subject = Mail.objects.get(type='seller_email').subject
        html_content = Template(Mail.objects.get(type='seller_email').mail).render(Context(context))
        msg = EmailMessage(subject, html_content, config.ORDER_FROM_EMAIL, email_list)
        msg.content_subtype = "html"
        msg.send()
    except Exception, e:
            text = 'Ошибка %s'%e
            subject = 'покупка'
            html_content = render_to_string('text.html',{'context': text})
            msg = EmailMessage(subject, html_content, config.ORDER_FROM_EMAIL, email_list)
            msg.content_subtype = "html"
            msg.send()


def get_cart(request):
    return render(request, 'order/cart.html', {'cart': ShoppingCart(request)})


def add_to_cart(request, product_id, quantity=1):
    back_link = "/"
    if request.META:
        back_link = request.META.get("HTTP_REFERER", "/")

    product = Product.objects.get(id=product_id)
    cart = ShoppingCart(request)

    if 'quantity' in request.POST:
        quantity = abs(int(request.POST.get('quantity')))
    messages.success(request, request.message_after_adding_the_goods_into_the_basket)

    for item in cart:
        if item.product == product:
            cart.update(item.id, item.quantity + quantity)
            return HttpResponseRedirect(back_link)

    item = cart.add(product, product.price, quantity)
    return HttpResponseRedirect(back_link)


def remove_from_cart(request, item_id):
    cart = ShoppingCart(request)
    cart.remove(item_id)
    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))


def clear_cart(request):
    cart = ShoppingCart(request)
    cart.clear()
    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))


def update_cart(request, item_id, quantity):
    cart = ShoppingCart(request)
    cart.update(item_id, quantity, True)
    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))


def check_cart(cart):
    mes = False
    for item in cart:
        if item.product:
            if item.price != item.product.price:
                item.price = item.product.price
                mes = True
        else:
            item.price = 0
            mes = True
        item.save()
    return mes

def checkout(request):
    cart = ShoppingCart(request)
    form = False

    breadcrumbs = [{"title": "Корзина"}]

    if request.GET.has_key("continue"):
        form = OrderForm()
        if check_cart(cart):
            try:
                messages.success(request, request.message_cart_changed)
            except:
                messages.success(request, u"Обратите внимание, цены на товары обновлены")

    if request.method == 'POST':
        form = OrderForm(request.POST)
        if form.is_valid():
            if cart.quantity():
                order = form.save(commit=False)
                statuses = OrderStatus.objects.filter(is_initial=True)
                if statuses:
                    order.status = statuses[0]
                order.total_cost = cart.summary()
                order.save()
                mes = False
                for item in cart:
                    if item.price > 0:
                        OrderItem.objects.create(
                            order=order,
                            product=item.get_item(),
                            price=item.price,
                            quantity=item.quantity,
                        )
                        item.delete()
                    else:
                        mes = True
                if mes:
                    try:
                        messages.success(request, request.message_cart_not_emp)
                    except:
                        messages.success(request, u"В корзине остались товары которые сейчас купить нельзя")

                # cart.clear()
                customer_email(request, order)
                seller_email(request, order)

                messages.success(request, request.message_after_successful_order)

    context = {'form': form, 'cart': cart, 'breadcrumbs': breadcrumbs}

    return render(request, 'order/cart.html', context)

templates/order/tags/cart_item.html
{% load thumbnail catalog_filters %}
<tr class="cart-product{% if forloop.last %} last{% endif %}{% if forloop.first %} first{% endif %}" item_id="{{ item.id }}">
    <td class="cart-product-image">
        <a href="{{ item.product.get_absolute_url }}" title="{{ item.product.name }}">
            <div class="product-image-wrapper">
                {% if item.product.get_primary_image %}
                    {% with item.product.get_primary_image.file as image %}
                    {% if image|is_portrait %}
                        {% thumbnail image "x122" crop="center" upscale=False quality=100 as im %}
                            <img src="{{ im.url }}" alt="{{ item.name }}">
                        {% endthumbnail %}
                    {% else %}
                        {% thumbnail image "161" crop="center" upscale=False quality=100 as im %}
                            <img src="{{ im.url }}" alt="{{ item.name }}">
                        {% endthumbnail %}
                    {% endif %}
                    {% endwith %}
                {% else %}
                    <img src="http://placehold.it/161x122" alt="{{ item.name }}">
                {% endif %}
            </div>
        </a>
    </td>
    <td class="cart-product-details">
        <a href="{{ item.product.get_absolute_url }}" title="{{ item.product.name }}">
            <div class="product-title">{{ item.product.name }}</div>
        </a>
        <div class="product-short-desc tmce">
            {% autoescape off %}{{ item.product.short_description }}{% endautoescape %}
        </div>
    </td>
    <td class="cart-product-price">
        {{ item.product.get_price }} руб.
    </td>
    <td class="cart-product-quantity">
        <div class="frame">
            <a href="{% url "order:update_cart" item.id -1 %}" class="tiny-button subtract"></a>
            <div class="product-q">{{ item.quantity }}</div>
            <a href="{% url "order:update_cart" item.id 1 %}" class="tiny-button add"></a
        </div>
    </td>
    <td class="cart-product-total-price">
        <div class="num">{{ item.total_price|format_price }} руб.</div>
        <a href="{% url "order:remove_from_cart" item.id %}" class="remove-from-cart">&#215;</a>
    </td>
</tr>

templates/order/tags/cart_widget.html
{% load pytils_numeral catalog_filters %}

{% if cart.quantity %}

			<div class="blc-oder">
				<div class="panel">
					<div class="panel_body">
						<div class="cart">
                            <div class="cart_widget active">
                                <a href="{% url "order:checkout" %}" class="cart_widget-btn"><i></i></a>
                                <div class="cart_widget-txt">
                                    <span>{{ cart.quantity }} {{ cart.quantity|choose_plural:"Товар, Товара, Товаров" }} на сумму {{ cart.summary|format_price }} руб.</span><br>
                                    <a href="{% url "order:checkout" %}">Оформить заказ</a>
                                </div>
                            </div>
						</div>
					</div>
				</div>

			</div>

{% else %}

			<div class="blc-oder">
				<div class="panel">
					<div class="panel_body">
						<div class="cart">
                            <div class="cart_widget">
                                <div class="cart_widget-btn"><i></i></div>
                                <div class="cart_widget-txt empty">
                                    <span>Корзина пуста</span><br>
                                </div>
                            </div>
						</div>
					</div>
				</div>

			</div>
{% endif %}

templates/order/tags/cart_widget_old.html
{% load pytils_numeral catalog_filters %}

{% if cart.quantity %}
    <div class="cart_widget active">
        <a href="{% url "order:checkout" %}" class="cart_widget-btn"><i></i></a>
        <div class="cart_widget-txt">
            <span>{{ cart.quantity }} {{ cart.quantity|choose_plural:"Товар, Товара, Товаров" }} на сумму {{ cart.summary|format_price }} руб.</span><br>
            <a href="{% url "order:checkout" %}">Оформить заказ</a>
        </div>
    </div>
{% else %}
    <div class="cart_widget">
        <div class="cart_widget-btn"><i></i></div>
        <div class="cart_widget-txt empty">
            <span>Корзина пуста</span><br>
        </div>
    </div>
{% endif %}

templates/order/tags/order_form.html
<form class="form order-form" method="post" action="{% url "order:checkout" %}">
    {% csrf_token %}
    <table>
        <tbody>
            {% for field in form %}
            <tr>
                <td class="left">{{ field.label }}{% if field.field.required %}<span class="required">*</span>{% endif %}</td>
                <td class="row {% if field.errors %}error{% endif %}">
                    {{ field }}
                </td>
            </tr>
            {% endfor %}

            <tr>
                <td class="left"></td>
                <td><button class="cart-button" type="submit">Оформить</button></td>
            </tr>
        </tbody>
    </table>
</form>

templates/order/tags/webstocks.html
{% for o in opts %}
    <option {% if forloop.first %}selected="selected"{% endif %} value="{{ o.id }}">{{ o.name }}</option>
{% endfor %}